services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
      target: development
    container_name: cabinet_backend
    restart: unless-stopped
    working_dir: /var/www/html
    env_file:
      - ./backend/.env.development
    volumes:
      - ./backend:/var/www/html
    networks:
      - cabinet_network
    depends_on:
      - postgres
    expose:
      - "8000"

  frontend:
    container_name: cabinet_frontend
    networks:
      - cabinet_network
    expose:
      - "5173"

  postgres:
    image: postgres:16-alpine
    container_name: cabinet_postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cabinet_network

  nginx:
    image: nginx:alpine
    container_name: cabinet_nginx
    restart: unless-stopped
    networks:
      - cabinet_network
    depends_on:
      - backend

networks:
  cabinet_network:
    driver: bridge

volumes:
  postgres_data:
